In [2]:
#attributes in R 
#object 

friends <- 1:5
names(friends) <- 
  c("Bob" , "anu" , "ram " , " jack")
names(friends)

[1] "Bob"   "anu"   "ram "  " jack" NA

In [3]:
# Matrix 

m <- matrix(1:4 , 2, 2)
dimnames(m) <-
list (c("a" , "b") , c("c" ,"d"))
m

c d
a 1 3
b 2 4

In [4]:
# dimension function 
dim(mtcars)

[1] 32 11

In [5]:
# class 
class(friends)

[1] "integer"

In [6]:
friends <- 1:5
names(friends) <- 
  c("Bob" , "anu" , "ram " , " jack")


class(friends)
friends

[1] "integer"

Bob   anu  ram   jack  <NA> 
    1     2     3     4     5

In [7]:
# length()
length(friends)

[1] 5

In [8]:
# View()
# head() helps us to visualize only the upper part of a data
# tail() helps us to visualize only the last part of any data
# range(name_vector) to know range of the features
# operators 

a <-3
b <-5
a+b

[1] 8

In [9]:
a-b

[1] -2

In [10]:
a*b

[1] 15

In [12]:
a <- 1:4
is.vector(a) # Bool func which speaks wthr it is vec or not 
# matrix : is.matrix()

[1] TRUE

In [13]:
a <- 1:6
b <- 2:7

a+b

[1]  3  5  7  9 11 13

In [14]:
a <- 1:4 
a[-3]

[1] 1 2 4

In [15]:
# matrix operation 

a <- matrix( 1:4 , 2 , 2)
a

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [16]:
b <- matrix(2:5, 2 , 2)
b

[,1] [,2]
[1,] 2    4   
[2,] 3    5

In [17]:
a+b

[,1] [,2]
[1,] 3    7   
[2,] 5    9

In [22]:
# transpose operation
# t()

a <- matrix(20 : 23 , 2 , 2)
a

[,1] [,2]
[1,] 20   22  
[2,] 21   23

In [23]:
b <- t(a)
b

# finding diagonal matrix diag()

[,1] [,2]
[1,] 20   21  
[2,] 22   23

In [24]:
# functions
# mean , medean , mode 

my_data <- rnorm(100)
mean(my_data)

[1] -0.01132588

In [25]:
mean(x = my_data)

[1] -0.01132588

In [26]:
mean(x= my_data , rnorm= FALSE)

[1] -0.01132588

In [29]:
 my_function1 <- 
function(num=1){
    res= 0 
    num=num*3
    res=num+4
}
print(my_function1())

[1] 7


In [30]:
my_function1 <- function(x , y)
    { 
    x^2+y/z}
# Lexical scoping - function defined  & global env >> R 
# Dynamic scoping - function called 



In [ ]:
# install pkg in R
install.packages("pkg-name")

# how to call a pkg in py 
# import matplotlib 
# in R 
library(pkg-name)
# reading txt file in R
mydata <- read.table("data.txt")
#csv in R
mydata <- read.csv (r"path to file")
mydata
# to deal wil excel value 
library(readr) #data reading line by line 
# Java based pkg in R XLconnect
library(XLConnect)
#excel : xlsx()
library(xlsx)
read.xlsx()
#SQL file 
mydata=dbConnect(MySQL(), user='user'
password = 'password'
dbname = 'database_name' , host='host')